packageName: apicast-operator
channels:
- name: threescale-2.10
  currentCSV: apicast-operator.v0.4.0
- name: threescale-2.8
  currentCSV: apicast-operator.v0.2.4
- name: threescale-2.9
  currentCSV: apicast-operator.v0.3.1
defaultChannel: threescale-2.10
