apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "performance.openshift.io/v1alpha1",
          "kind": "PerformanceProfile",
          "metadata": {
            "name": "example-performanceprofile"
          },
          "spec": {
            "additionalKernelArgs": [
              "nmi_watchdog=0",
              "audit=0",
              "mce=off",
              "processor.max_cstate=1",
              "idle=poll",
              "intel_idle.max_cstate=0"
            ],
            "cpu": {
              "isolated": "2-3",
              "reserved": "0-1"
            },
            "hugepages": {
              "defaultHugepagesSize": "1G",
              "pages": [
                {
                  "count": 2,
                  "node": 0,
                  "size": "1G"
                }
              ]
            },
            "nodeSelector": {
              "node-role.kubernetes.io/performance": ""
            },
            "realTimeKernel": {
              "enabled": true
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: OpenShift Optional
    certified: 'false'
    containerImage: registry.redhat.io/openshift4/performance-addon-rhel8-operator@sha256:6d70ae0cce58d1608196fbd26090a0c3e49af2d67eb9ca36f772e8f6c888bbf9
    description: Operator to optimize OpenShift clusters for applications sensitive
      to CPU and network latency.
    olm.skipRange: '>=4.4.0 <4.5.3'
    repository: https://github.com/openshift-kni/performance-addon-operators
    support: Red Hat
  name: performance-addon-operator.v4.5.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: PerformanceProfile is the Schema for the performanceprofiles API.
      displayName: Performance Profile
      kind: PerformanceProfile
      name: performanceprofiles.performance.openshift.io
      version: v1alpha1
  description: |+
    |2-

        DEVELOPER PREVIEW! There is no official support, do not use in production or any other important clusters.
        The operator affects worker nodes and can cause instability or service disruption.

        Performance Addon Operator provides the ability to enable advanced node performance tunings on a set of nodes.

  displayName: Performance Addon Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ''
          resources:
          - events
          verbs:
          - '*'
        - apiGroups:
          - performance.openshift.io
          resources:
          - performanceprofiles
          - performanceprofiles/finalizers
          - performanceprofiles/status
          verbs:
          - '*'
        - apiGroups:
          - config.openshift.io
          resources:
          - featuregates
          verbs:
          - '*'
        - apiGroups:
          - machineconfiguration.openshift.io
          resources:
          - machineconfigs
          - machineconfigpools
          - kubeletconfigs
          verbs:
          - '*'
        - apiGroups:
          - tuned.openshift.io
          resources:
          - tuneds
          verbs:
          - '*'
        serviceAccountName: performance-operator
      deployments:
      - name: performance-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: performance-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: performance-operator
            spec:
              containers:
              - command:
                - performance-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: performance-operator
                image: registry.redhat.io/openshift4/performance-addon-rhel8-operator@sha256:6d70ae0cce58d1608196fbd26090a0c3e49af2d67eb9ca36f772e8f6c888bbf9
                imagePullPolicy: Always
                name: performance-operator
                resources: {}
              serviceAccountName: performance-operator
      permissions:
      - rules:
        - apiGroups:
          - ''
          resources:
          - pods
          - services
          - services/finalizers
          - configmaps
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - performance-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - '*'
        serviceAccountName: performance-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - numa
  - realtime
  - cpu pinning
  - hugepages
  links:
  - name: Source Code
    url: https://github.com/openshift-kni/performance-addon-operators
  maintainers:
  - email: openshift-operators@redhat.com
    name: Red Hat
  maturity: alpha
  provider:
    name: Red Hat
  version: 4.5.3
  relatedImages:
  - name: performance-addon-rhel8-operator-6d70ae0cce58d1608196fbd26090a0c3e49af2d67eb9ca36f772e8f6c888bbf9-annotation
    image: registry.redhat.io/openshift4/performance-addon-rhel8-operator@sha256:6d70ae0cce58d1608196fbd26090a0c3e49af2d67eb9ca36f772e8f6c888bbf9
  - name: performance-operator
    image: registry.redhat.io/openshift4/performance-addon-rhel8-operator@sha256:6d70ae0cce58d1608196fbd26090a0c3e49af2d67eb9ca36f772e8f6c888bbf9
