---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    "operatorframework.io/suggested-namespace": openshift-aws-ebs-csi-driver-operator
    containerImage: registry.redhat.io/openshift4/ose-aws-ebs-csi-driver-rhel7-operator@sha256:ac052af902a6e3cd51b6f85a5181a3339740eef3f18a47f02621db05bdeae125
    categories: "Storage"
    capabilities: Full Lifecycle
    description: |-
      Operator to install and maintain the AWS EBS CSI Driver on a cluster.
    certified: "false"
    support: https://github.com/openshift/aws-ebs-csi-driver-operator
    repository: https://github.com/openshift/aws-ebs-csi-driver-operator
    createdAt: 2020-03-24:13:08:00
    olm.skipRange: '>=4.3.0 <4.5.18'
    alm-examples: |-
      [
        {
          "apiVersion": "csi.openshift.io/v1alpha1",
          "kind": "AWSEBSDriver",
          "metadata": {
            "name": "cluster"
          },
          "spec": {
            "managementState": "Managed",
            "logLevel": "Normal",
            "operatorLogLevel": "Normal"
          }
        }
      ]
  name: aws-ebs-csi-driver-operator.v4.5.18
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  maturity: alpha
  version: 4.5.18
  minKubeVersion: 1.17.0
  description: |-
     Operator to install and maintain the AWS EBS CSI Driver on a cluster.
  displayName: AWS EBS CSI Driver Operator
  keywords: ['aws', 'CSI']
  maintainers:
  - name: Red Hat
    email: aos-storage-staff@redhat.com
  provider:
    name: Red Hat
  labels:
    alm-owner-metering: aws-ebs-csi-driver-operator
    alm-status-descriptors: aws-ebs-csi-driver-operator.v4.5.18
  selector:
    matchLabels:
      alm-owner-metering: aws-ebs-csi-driver-operator
  installModes:
  - type: OwnNamespace
    supported: false
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: aws-ebs-csi-driver-operator
        rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
      clusterPermissions:
      - serviceAccountName: aws-ebs-csi-driver-operator
        rules:
        - apiGroups:
          - "security.openshift.io"
          resources:
          - securitycontextconstraints
          verbs:
          - use
          resourceNames:
          - privileged
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - "*"
          resourceNames:
          - extension-apiserver-authentication
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          - roles
          - rolebindings
          verbs:
          - watch
          - list
          - get
          - create
          - delete
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - list
          - create
          - watch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - watch
          - create
          - patch
          - delete
          - update
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - create
          - delete
          - list
          - get
          - watch
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - ""
          resources:
          - "persistentvolumeclaims/status"
          verbs:
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
        - apiGroups:
          - storage.k8s.io
          resources:
          - volumeattachments
          verbs:
          - get
          - list
          - watch
          - update
          - delete
          - create
          - patch
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotcontents/status
          verbs:
          - update
          - patch
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          - csinodes
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - "*"
          resources:
          - events
          verbs:
          - get
          - patch
          - create
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotclasses
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotcontents
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - csidrivers
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - csi.openshift.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - cloudcredential.openshift.io
          resources:
          - credentialsrequests
          verbs:
          - "*"
        - apiGroups:
            - config.openshift.io
          resources:
            - infrastructures
          verbs:
            - get
            - list
            - watch
      deployments:
      - name: aws-ebs-csi-driver-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: aws-ebs-csi-driver-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: aws-ebs-csi-driver-operator
            spec:
              priorityClassName: system-cluster-critical
              serviceAccountName: aws-ebs-csi-driver-operator
              tolerations:
              - key: CriticalAddonsOnly
                operator: Exists
              containers:
              - name: aws-ebs-csi-driver-operator
                image: registry.redhat.io/openshift4/ose-aws-ebs-csi-driver-rhel7-operator@sha256:ac052af902a6e3cd51b6f85a5181a3339740eef3f18a47f02621db05bdeae125
                imagePullPolicy: Always
                args:
                - start
                env:
                - name: RELATED_IMAGE_DRIVER
                  value: registry.redhat.io/openshift4/ose-aws-ebs-csi-driver-rhel7@sha256:e08f56e76c15b076fa13debc7db6531eb5709d70ebbd4cb54ed9ab81ca2eb055
                - name: RELATED_IMAGE_PROVISIONER
                  value: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel7@sha256:4206ce047d1c3c9c809bc9c9ab800b4394957758c8d1c390a1702ecfe573ee35
                - name: RELATED_IMAGE_ATTACHER
                  value: registry.redhat.io/openshift4/ose-csi-external-attacher@sha256:7d01251ed3be8aa0f3e2ba7b225290e580cee9e668e74efae7ba35dcbf458419
                - name: RELATED_IMAGE_RESIZER
                  value: registry.redhat.io/openshift4/ose-csi-external-resizer-rhel7@sha256:ee599e723a2517e83cddae84fdba56c893771cc34942a3d6d66df6e4d8d0ffcb
                - name: RELATED_IMAGE_SNAPSHOTTER
                  value: registry.redhat.io/openshift4/ose-csi-external-snapshotter-rhel7@sha256:db56a08f1d13a6a98271ee1eca3818ff7ee14e09daec496ae6cf3d8323187afa
                - name: RELATED_IMAGE_NODE_DRIVER_REGISTRAR
                  value: registry.redhat.io/openshift4/ose-csi-node-driver-registrar@sha256:38d196311f05c8b1902654572d432760ae642885a4239987f887225e2afb5fce
                - name: RELATED_IMAGE_LIVENESS_PROBE
                  value: registry.redhat.io/openshift4/ose-csi-livenessprobe@sha256:ee0b11f26f0000b1315dd204adde1a58b221e727be63d1d842a90d6cd33c90b4
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: aws-ebs-csi-driver-operator

  customresourcedefinitions:
    owned:
    - kind: AWSEBSDriver
      displayName: EBS CSI Driver
      group: csi.openshift.io
      name: awsebsdrivers.csi.openshift.io
      description: Manage EBS CSI driver for OpenShift
      version: v1alpha1
      specDescriptors:
        - description: Management state of operator
          displayName: Managementstate
          path: managementState
        - description: Log level of operator
          displayName: LogLevel
          path: logLevel
      statusDescriptors:
        - description: Last generation of this object
          displayName: ObservedGeneration
          path: observedGeneration
        - description: Last known condition of the operator
          displayName: Conditions
          path: conditions
          x-descriptors:
            - 'urn:alm:descriptor:io.kubernetes.conditions'
  relatedImages:
  - name: ose-aws-ebs-csi-driver-rhel7
    image: registry.redhat.io/openshift4/ose-aws-ebs-csi-driver-rhel7@sha256:e08f56e76c15b076fa13debc7db6531eb5709d70ebbd4cb54ed9ab81ca2eb055
  - name: ose-aws-ebs-csi-driver-rhel7-operator
    image: registry.redhat.io/openshift4/ose-aws-ebs-csi-driver-rhel7-operator@sha256:ac052af902a6e3cd51b6f85a5181a3339740eef3f18a47f02621db05bdeae125
  - name: ose-csi-external-attacher
    image: registry.redhat.io/openshift4/ose-csi-external-attacher@sha256:7d01251ed3be8aa0f3e2ba7b225290e580cee9e668e74efae7ba35dcbf458419
  - name: ose-csi-external-provisioner-rhel7
    image: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel7@sha256:4206ce047d1c3c9c809bc9c9ab800b4394957758c8d1c390a1702ecfe573ee35
  - name: ose-csi-external-resizer-rhel7
    image: registry.redhat.io/openshift4/ose-csi-external-resizer-rhel7@sha256:ee599e723a2517e83cddae84fdba56c893771cc34942a3d6d66df6e4d8d0ffcb
  - name: ose-csi-external-snapshotter-rhel7
    image: registry.redhat.io/openshift4/ose-csi-external-snapshotter-rhel7@sha256:db56a08f1d13a6a98271ee1eca3818ff7ee14e09daec496ae6cf3d8323187afa
  - name: ose-csi-livenessprobe
    image: registry.redhat.io/openshift4/ose-csi-livenessprobe@sha256:ee0b11f26f0000b1315dd204adde1a58b221e727be63d1d842a90d6cd33c90b4
  - name: ose-csi-node-driver-registrar
    image: registry.redhat.io/openshift4/ose-csi-node-driver-registrar@sha256:38d196311f05c8b1902654572d432760ae642885a4239987f887225e2afb5fce
